-- MySQL Script generated by MySQL Workbench
-- Thu Apr 16 23:52:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema u892058990_AOMJK
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `u892058990_AOMJK` ;

-- -----------------------------------------------------
-- Schema u892058990_AOMJK
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u892058990_AOMJK` DEFAULT CHARACTER SET utf8 ;
USE `u892058990_AOMJK` ;

-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`appmovil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`appmovil` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `temp` VARCHAR(10) NOT NULL,
  `hume` VARCHAR(10) NOT NULL,
  `soni` VARCHAR(10) NOT NULL,
  `radi` VARCHAR(10) NOT NULL,
  `fecha` date NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`loteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`loteria` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `f1` VARCHAR(10) NOT NULL,
  `f2` VARCHAR(10) NOT NULL,
  `f3` VARCHAR(10) NOT NULL,
  `carton` VARCHAR(10) NOT NULL,
  `fecha` datetime NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit01`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit01` (
  `idpers` INT NOT NULL AUTO_INCREMENT,
  `dateofbirth` DATE NOT NULL,
  `address` VARCHAR(60) NULL,
  `frstnam` VARCHAR(45) NOT NULL,
  `scondnam` VARCHAR(45) NULL,
  `frstlstnam` VARCHAR(45) NOT NULL,
  `scondlstnam` VARCHAR(45) NULL,
  `numphone` VARCHAR(15) NULL,
  PRIMARY KEY (`idpers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `idpers` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_users_persons1_idx` (`idpers` ASC) ,
  CONSTRAINT `fk_users_persons1`
    FOREIGN KEY (`idpers`)
    REFERENCES `u892058990_AOMJK`.`audit01` (`idpers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`password_resets` (
  `idpass` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`idpass`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`migrations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`permissions` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `slug` VARCHAR(120) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`permission_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`permission_user` (
  `id` BIGINT(20) NOT NULL,
  `permission_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_audit02_audit051_idx` (`permission_id` ASC) ,
  INDEX `fk_audit02_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_audit02_audit051`
    FOREIGN KEY (`permission_id`)
    REFERENCES `u892058990_AOMJK`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audit02_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `u892058990_AOMJK`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`roles` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `slug` VARCHAR(120) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `state` ENUM('A', 'R') NOT NULL DEFAULT 'A',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `special` ENUM('all-access', 'no-access') NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`permission_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`permission_role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT(20) NOT NULL,
  `permission_id` BIGINT(20) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_audit03_audit061_idx` (`role_id` ASC) ,
  INDEX `fk_audit03_audit051_idx` (`permission_id` ASC) ,
  CONSTRAINT `fk_audit03_audit061`
    FOREIGN KEY (`role_id`)
    REFERENCES `u892058990_AOMJK`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audit03_audit051`
    FOREIGN KEY (`permission_id`)
    REFERENCES `u892058990_AOMJK`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`role_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`role_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_audit04_audit061_idx` (`role_id` ASC) ,
  INDEX `fk_audit04_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_audit04_audit061`
    FOREIGN KEY (`role_id`)
    REFERENCES `u892058990_AOMJK`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audit04_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `u892058990_AOMJK`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit07`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit07` (
  `id_sys` INT NOT NULL AUTO_INCREMENT,
  `sys_act` ENUM('C', 'R', 'U', 'D') NOT NULL,
  `sys_date` DATETIME NOT NULL,
  `iduser` BIGINT NOT NULL,
  PRIMARY KEY (`id_sys`),
  INDEX `fk_audsys_users1_idx` (`iduser` ASC) ,
  CONSTRAINT `fk_audsys_users1`
    FOREIGN KEY (`iduser`)
    REFERENCES `u892058990_AOMJK`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit08`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit08` (
  `idauddsys` INT NOT NULL AUTO_INCREMENT,
  `idsys` INT NOT NULL,
  `dsyscontroller` VARCHAR(45) NOT NULL,
  `dsysmethod` VARCHAR(45) NOT NULL,
  `dsysip` VARCHAR(45) NOT NULL,
  `dsysbrowser` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idauddsys`),
  INDEX `fk_auddsys_audsys1_idx` (`idsys` ASC) ,
  CONSTRAINT `fk_auddsys_audsys1`
    FOREIGN KEY (`idsys`)
    REFERENCES `u892058990_AOMJK`.`audit07` (`id_sys`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit20`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit20` (
  `idtrans` INT NOT NULL AUTO_INCREMENT,
  `transtable` VARCHAR(45) NOT NULL,
  `audtransacc` ENUM('I', 'U', 'D') NOT NULL,
  `transuser` VARCHAR(45) NOT NULL,
  `transdate` DATETIME NOT NULL,
  PRIMARY KEY (`idtrans`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit19`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit19` (
  `iddettran` INT NOT NULL AUTO_INCREMENT,
  `idtrans` INT NOT NULL,
  `dtranfile` VARCHAR(45) NOT NULL,
  `dtranvnew` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddettran`),
  INDEX `fk_auddtran_audtrans1_idx` (`idtrans` ASC) ,
  CONSTRAINT `fk_auddtran_audtrans1`
    FOREIGN KEY (`idtrans`)
    REFERENCES `u892058990_AOMJK`.`audit20` (`idtrans`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit12`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit12` (
  `idfilms` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `duration` VARCHAR(10) NOT NULL,
  `premiere` VARCHAR(10) NOT NULL,
  `image` BLOB NULL,
  PRIMARY KEY (`idfilms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit15`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit15` (
  `idrooms` INT NOT NULL AUTO_INCREMENT,
  `quality` VARCHAR(45) NOT NULL,
  `image` BLOB NOT NULL,
  PRIMARY KEY (`idrooms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit14`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit14` (
  `idfunction` INT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NOT NULL,
  `price` DOUBLE NOT NULL,
  `idroomss` INT NOT NULL,
  `idfilms` INT NOT NULL,
  PRIMARY KEY (`idfunction`),
  INDEX `idroomss_idx` (`idroomss` ASC) ,
  INDEX `fk_function_films1_idx` (`idfilms` ASC) ,
  CONSTRAINT `idrooms`
    FOREIGN KEY (`idroomss`)
    REFERENCES `u892058990_AOMJK`.`audit15` (`idrooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_function_films1`
    FOREIGN KEY (`idfilms`)
    REFERENCES `u892058990_AOMJK`.`audit12` (`idfilms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit16`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit16` (
  `idseating` INT NOT NULL AUTO_INCREMENT,
  `row` INT(2) NOT NULL,
  `number` INT(2) NOT NULL,
  `idrooms` INT NOT NULL,
  PRIMARY KEY (`idseating`),
  INDEX `idrooms_idx` (`idrooms` ASC) ,
  CONSTRAINT `idrooms2`
    FOREIGN KEY (`idrooms`)
    REFERENCES `u892058990_AOMJK`.`audit15` (`idrooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit21`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit21` (
  `idpaytyp` INT NOT NULL AUTO_INCREMENT,
  `detpay` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpaytyp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit22`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit22` (
  `idticketsale` INT NOT NULL AUTO_INCREMENT,
  `salevalue` DOUBLE NOT NULL,
  `saletime` DATETIME NOT NULL,
  `idfunction` INT NOT NULL,
  `idpaytyp` INT NOT NULL,
  `id` BIGINT NOT NULL,
  `idseating` INT NOT NULL,
  PRIMARY KEY (`idticketsale`),
  INDEX `idpaymenttype_idx` (`idpaytyp` ASC) ,
  INDEX `idfuncion_idx` (`idfunction` ASC) ,
  INDEX `idusers_idx` (`id` ASC) ,
  INDEX `fk_audit22_audit161_idx` (`idseating` ASC) ,
  CONSTRAINT `idpaymenttype`
    FOREIGN KEY (`idpaytyp`)
    REFERENCES `u892058990_AOMJK`.`audit21` (`idpaytyp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idfuncion`
    FOREIGN KEY (`idfunction`)
    REFERENCES `u892058990_AOMJK`.`audit14` (`idfunction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`id`)
    REFERENCES `u892058990_AOMJK`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audit22_audit161`
    FOREIGN KEY (`idseating`)
    REFERENCES `u892058990_AOMJK`.`audit16` (`idseating`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit09`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit09` (
  `idactors` INT NOT NULL AUTO_INCREMENT,
  `surnames` VARCHAR(45) NOT NULL,
  `names` VARCHAR(45) NOT NULL,
  `image` BLOB NOT NULL,
  PRIMARY KEY (`idactors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit13`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit13` (
  `iddirectors` INT NOT NULL AUTO_INCREMENT,
  `surnames` VARCHAR(45) NOT NULL,
  `names` VARCHAR(45) NOT NULL,
  `image` BLOB NOT NULL,
  PRIMARY KEY (`iddirectors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit10`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit10` (
  `idactorxfil` INT NOT NULL AUTO_INCREMENT,
  `idactor` INT NOT NULL,
  `idfilms` INT NOT NULL,
  PRIMARY KEY (`idactorxfil`),
  INDEX `idactor_idx` (`idactor` ASC) ,
  INDEX `idfilms_idx` (`idfilms` ASC) ,
  CONSTRAINT `idactor`
    FOREIGN KEY (`idactor`)
    REFERENCES `u892058990_AOMJK`.`audit09` (`idactors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idfilms`
    FOREIGN KEY (`idfilms`)
    REFERENCES `u892058990_AOMJK`.`audit12` (`idfilms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit23`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit23` (
  `idfile` INT NOT NULL AUTO_INCREMENT,
  `route1` VARCHAR(200) NOT NULL,
  `extension1` ENUM('T', 'C') NOT NULL,
  `size1` VARCHAR(10) NOT NULL,
  `route2` VARCHAR(200) NOT NULL,
  `extension2` ENUM('T', 'C') NOT NULL,
  `size2` VARCHAR(10) NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `diffsize` ENUM('Y', 'N') NOT NULL,
  `detdiffsize` VARCHAR(100) NOT NULL,
  `diffinfo` ENUM('Y', 'N') NOT NULL,
  `detdiffinfo` TEXT NOT NULL,
  `state` ENUM('A', 'R') NOT NULL DEFAULT 'A',
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`idfile`),
  INDEX `fk_audit23_users1_idx` (`id` ASC) ,
  CONSTRAINT `fk_audit23_users1`
    FOREIGN KEY (`id`)
    REFERENCES `u892058990_AOMJK`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit11`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit11` (
  `idaudit11` INT NOT NULL AUTO_INCREMENT,
  `iddirectors` INT NOT NULL,
  `idfilms` INT NOT NULL,
  PRIMARY KEY (`idaudit11`),
  INDEX `fk_audit111_audit131_idx` (`iddirectors` ASC) ,
  INDEX `fk_audit111_audit121_idx` (`idfilms` ASC) ,
  CONSTRAINT `fk_audit111_audit131`
    FOREIGN KEY (`iddirectors`)
    REFERENCES `u892058990_AOMJK`.`audit13` (`iddirectors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audit111_audit121`
    FOREIGN KEY (`idfilms`)
    REFERENCES `u892058990_AOMJK`.`audit12` (`idfilms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit24`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit24` (
  `codigo` CHAR(30) NOT NULL,
  `nombre` CHAR(30) NOT NULL,
  `nofactura` CHAR(30) NOT NULL,
  `valor` CHAR(30) NOT NULL,
  `concepto` CHAR(30) NOT NULL,
  `idfile` INT NOT NULL,
  INDEX `fk_audit24_audit231_idx` (`idfile` ASC) ,
  CONSTRAINT `fk_audit24_audit231`
    FOREIGN KEY (`idfile`)
    REFERENCES `u892058990_AOMJK`.`audit23` (`idfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u892058990_AOMJK`.`audit25`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u892058990_AOMJK`.`audit25` (
  `codigo` CHAR(30) NOT NULL,
  `nombre` CHAR(30) NOT NULL,
  `nofactura` CHAR(30) NOT NULL,
  `valor` CHAR(30) NOT NULL,
  `concepto` CHAR(30) NOT NULL,
  `idfile` INT NOT NULL,
  INDEX `fk_audit25_audit231_idx` (`idfile` ASC) ,
  CONSTRAINT `fk_audit25_audit231`
    FOREIGN KEY (`idfile`)
    REFERENCES `u892058990_AOMJK`.`audit23` (`idfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;






insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Store roles','roles.store','Store roles',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Browse roles','roles.index','List and browse all system Rol',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Create roles','roles.create','Create rol in all system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Update rol','roles.update','Update any data of a system Rol',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('View role detail','roles.show','See in detail each system Rol',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Delete rol','roles.destoy','remove any Rol from the system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Edition rol','roles.edit','allows the form view',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Browse Audsys','audit07.index','List and browse all system Audsys',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('View Audsys','audit07.show','See in detail each system Audsys',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Delete Audsys','audit07.destroy','Remove any Audsys',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Store Actors','audit09.store','Store Actors',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Browse Actors','audit09.index','List and browse all system Actors',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Create Actors','audit09.create','Create Actors in all system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Update Actors','audit09.update','Update any data of a system Actors',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('View Actors detail','audit09.show','See in detail each system Actors',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Delete Actors','audit09.destoy','remove any Actors from the system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Edition Actors','audit09.edit','allows the form view',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Store Directors','audit13.store','Store Directors',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Browse Directors','audit13.index','List and browse all system Directors',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Create Directors','audit13.create','Create Directors in all system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Update Directors','audit13.update','Update any data of a system Directors',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('View Directors detail','audit13.show','See in detail each system Directors',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Delete Directors','audit13.destoy','remove any Directors from the system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Edition Directors','audit13.edit','allows the form view',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Store Films','audit12.store','Store Films',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Browse Films','audit12.index','List and browse all system Films',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Create Films','audit12create','Create Films in all system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Update Films','audit12.update','Update any data of a system Films',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('View Films detail','audit12.show','See in detail each system Films',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Delete Films','audit12.destoy','remove any Films from the system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Edition Films','audit12.edit','allows the form view',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Store Rooms','audit15.store','Store Rooms',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Browse Rooms','audit15.index','List and browse all system Rooms',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Create Rooms','audit15.create','Create Rooms in all system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Update Rooms','audit15.update','Update any data of a system Rooms',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('View Rooms detail','audit15.show','See in detail each system Rooms',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Delete Rooms','audit15.destoy','remove any Rooms from the system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Edition Rooms','audit15.edit','allows the form view',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Store Seating','audit16.store','Store Seating',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Browse Seating','audit16.index','List and browse all system Seating',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Create Seating','audit16.create','Create Seating in all system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Update Seating','audit16.update','Update any data of a system Seating',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('View Seating detail','audit16.show','See in detail each system Seating',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Delete Seating','audit16.destoy','remove any Seating from the system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Edition Seating','audit16.edit','allows the form view',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Store Functions','audit14.store','Store Functions',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Browse Functions','audit14.index','List and browse all system Functions',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Create Functions','audit14.create','Create Functions in all system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Update Functions','audit14.update','Update any data of a system Functions',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('View Functions detail','audit14.show','See in detail each system Functions',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Delete Functions','audit14.destoy','remove any Functions from the system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Edition Functions','audit14.edit','allows the form view',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Store ticketsale','audit22.store','Store ticketsale',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Browse ticketsale','audit22.index','List and browse all system ticketsale',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Create ticketsale','audit22.create','Create ticketsale in all system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Update ticketsale','audit22.update','Update any data of a system ticketsale',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('View ticketsale detail','audit22.show','See in detail each system ticketsale',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Delete ticketsale','audit22.destoy','remove any ticketsale from the system',now(),now());
insert into u892058990_AOMJK.permissions (name,slug,description,created_at,updated_at) values('Edition ticketsale','audit22.edit','allows the form view',now(),now());

insert into u892058990_AOMJK.roles (name,slug,description,created_at,updated_at,special) values('Admin','admin',NULL,now(),now(),"all-access");

insert into u892058990_AOMJK.users (name,email,password,created_at,updated_at) values("Johan Arley Garcia Herran","johan123garciaherran@gmail.com","$2y$10$PKc1cx7nKre39H0AkPIAI.iAG80CWKgth4QQP8Rt6nGAq4Z9/suAm",now(),now());
insert into u892058990_AOMJK.users (name,email,password,created_at,updated_at) values("Ricardo Rico Lozada","ricardorico101@gmail.com","$2y$10$Uqg65tD2sloCvI1emcHCve4B68avVP09SxZr7GhQm90IofFYQaltO",now(),now());


insert into u892058990_AOMJK.role_user (role_id,user_id,created_at,updated_at) values(1,1,now(),now());
insert into u892058990_AOMJK.role_user (role_id,user_id,created_at,updated_at) values(1,2,now(),now());
